export default [
  {
      "_id": "60bdaec612f275fc7451c57e",
      "title": "Star Trek: First Contact",
      "year": "1996",
      "released": "22 Nov 1996",
      "runtime": 111,
      "language": "English",
      "genre": "Action, Adventure, Drama, Sci-Fi, Thriller",
      "director": "Jonathan Frakes",
      "poster": "https://m.media-amazon.com/images/M/MV5BNTc4MTc3NTQ5OF5BMl5BanBnXkFtZTcwOTg0NjI4NA@@._V1_SX300.jpg"
  },
  {
      "_id": "60bd923db1b0d030af499dfc",
      "title": "Star Wars: Episode III - Revenge of the Sith",
      "year": "2005",
      "released": "19 May 2005",
      "runtime": 140,
      "language": "English",
      "genre": "Action, Adventure, Fantasy, Sci-Fi",
      "director": "George Lucas",
      "poster": "https://m.media-amazon.com/images/M/MV5BNTc4MTc3NTQ5OF5BMl5BanBnXkFtZTcwOTg0NjI4NA@@._V1_SX300.jpg"
  },
  {
      "_id": "60f4347981d4502964d88738",
      "title": "Python",
      "year": "2000",
      "released": "01 Aug 2001",
      "runtime": 99,
      "language": "English",
      "genre": "Action, Comedy, Horror, Sci-Fi, Thriller",
      "director": "Richard Clabaugh",
      "poster": "https://m.media-amazon.com/images/M/MV5BZGZlNWU0ZWEtNzY4MC00NDdmLTgzOTktOTgzMjBlNGMxN2ZmL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"
  },
  {
      "_id": "60bd9293b1b0d030af499dfd",
      "title": "Star Wars: Episode VI - Return of the Jedi",
      "year": "1983",
      "released": "25 May 1983",
      "runtime": 131,
      "language": "English",
      "genre": "Action, Adventure, Fantasy, Sci-Fi",
      "director": "Richard Marquand",
      "poster": "https://m.media-amazon.com/images/M/MV5BOWZlMjFiYzgtMTUzNC00Y2IzLTk1NTMtZmNhMTczNTk0ODk1XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg"
  },
  {
      "_id": "60e072778bd3549e372416d0",
      "title": "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
      "year": "1964",
      "released": "29 Jan 1964",
      "runtime": 95,
      "language": "English, Russian",
      "genre": "Comedy",
      "director": "Stanley Kubrick",
      "poster": "https://m.media-amazon.com/images/M/MV5BZWI3ZTMxNjctMjdlNS00NmUwLWFiM2YtZDUyY2I3N2MxYTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg"
  },
  {
      "_id": "6280a7a60a225942747116e8",
      "title": "A Better Tomorrow II",
      "year": "1987",
      "released": "18 Dec 1987",
      "runtime": 105,
      "language": "Mandarin, Cantonese, English",
      "genre": "Action, Crime, Drama",
      "director": "John Woo",
      "poster": "https://m.media-amazon.com/images/M/MV5BOGFkZTA4MWYtNTM3Mi00Y2ZhLWEzYmMtNzIwMDFmMWU1MzdjXkEyXkFqcGdeQXVyMTc3MjY3NTY@._V1_SX300.jpg"
  },
  {
      "_id": "6288cd5abab2a26da869478a",
      "title": "A Better Tomorrow",
      "year": "1986",
      "released": "03 Aug 1986",
      "runtime": 95,
      "language": "Cantonese, Mandarin, English",
      "genre": "Action, Crime, Drama",
      "director": "John Woo",
      "poster": "https://m.media-amazon.com/images/M/MV5BZTEzMTYwZDItODIyYy00MjRkLTljOWMtZDI0ZmNjN2JjOTEyXkEyXkFqcGdeQXVyNzgzODI1OTE@._V1_SX300.jpg"
  },
  {
      "_id": "60bdae0cb1b0d030af499e03",
      "title": "Harry Potter and the Prisoner of Azkaban",
      "year": "2004",
      "released": "04 Jun 2004",
      "runtime": 142,
      "language": "English",
      "genre": "Adventure, Family, Fantasy, Mystery",
      "director": "Alfonso Cuarón",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTY4NTIwODg0N15BMl5BanBnXkFtZTcwOTc0MjEzMw@@._V1_SX300.jpg"
  },
  {
      "_id": "628a3961a9f33000bec9ec4e",
      "title": "Cinderella",
      "year": "2015",
      "released": "13 Mar 2015",
      "runtime": 105,
      "language": "English",
      "genre": "Adventure, Drama, Family",
      "director": "Kenneth Branagh",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjMxODYyODEzN15BMl5BanBnXkFtZTgwMDk4OTU0MzE@._V1_SX300.jpg"
  },
  {
      "_id": "628a48023aff210e5ee450f0",
      "title": "Home",
      "year": "2015",
      "released": "27 Mar 2015",
      "runtime": 94,
      "language": "English, French",
      "genre": "Animation, Adventure, Comedy",
      "director": "Tim Johnson",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjExOTQ4MDMyMV5BMl5BanBnXkFtZTgwMTE3NDM2MzE@._V1_SX300.jpg"
  },
  {
      "_id": "60edaa178bd3549e372416fd",
      "title": "Friction",
      "year": "2030",
      "released": "27 Feb 2010",
      "runtime": 89,
      "language": "English",
      "genre": "Comedy, Drama, Mystery",
      "director": "Cullen Hoback",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTc5NzcxNzYxOV5BMl5BanBnXkFtZTcwMjE3ODk1Mw@@._V1_SX300.jpg"
  },
  {
      "_id": "60d9ca998bd3549e372416c8",
      "title": "Suicide Squad",
      "year": "2016",
      "released": "05 Aug 2016",
      "runtime": 123,
      "language": "English, Japanese, Spanish",
      "genre": "Action, Adventure, Fantasy",
      "director": "David Ayer",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjM1OTMxNzUyM15BMl5BanBnXkFtZTgwNjYzMTIzOTE@._V1_SX300.jpg"
  },
  {
      "_id": "60d9cd258bd3549e372416cb",
      "title": "Wonder Woman 1984",
      "year": "2020",
      "released": "25 Dec 2020",
      "runtime": 151,
      "language": "English",
      "genre": "Action, Adventure, Fantasy",
      "director": "Patty Jenkins",
      "poster": "https://m.media-amazon.com/images/M/MV5BYTlhNzJjYzYtNGU3My00ZDI5LTgzZDUtYzllYjU1ZmU0YTgwXkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_SX300.jpg"
  },
  {
      "_id": "60d9c7638bd3549e372416c7",
      "title": "Miss Americana",
      "year": "2020",
      "released": "31 Jan 2020",
      "runtime": 85,
      "language": "English",
      "genre": "Documentary, Biography, Music",
      "director": "Lana Wilson",
      "poster": "https://m.media-amazon.com/images/M/MV5BYzE5MTM2M2EtNzIzNy00M2NiLWE1N2EtNGFkZDAxMWEwOWU3XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg"
  },
  {
      "_id": "60f04a838bd3549e37241716",
      "title": "Star Wars: Episode IV - A New Hope",
      "year": "1977",
      "released": "25 May 1977",
      "runtime": 121,
      "language": "English",
      "genre": "Action, Adventure, Fantasy, Sci-Fi",
      "director": "George Lucas",
      "poster": "https://m.media-amazon.com/images/M/MV5BNTc4MTc3NTQ5OF5BMl5BanBnXkFtZTcwOTg0NjI4NA@@._V1_SX300.jpg"
  },
  {
      "_id": "60bdb19612f275fc7451c57f",
      "title": "Indiana Jones and the Temple of Doom",
      "year": "1984",
      "released": "23 May 1984",
      "runtime": 118,
      "language": "English, Sinhalese, Hindi",
      "genre": "Action, Adventure",
      "director": "Steven Spielberg",
      "poster": "https://m.media-amazon.com/images/M/MV5BMGI1NTk2ZWMtMmI0YS00Yzg0LTljMzgtZTg4YjkyY2E5Zjc0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg"
  },
  {
      "_id": "625aee7efefee031204ec584",
      "title": "The Batman",
      "year": "2022",
      "released": "04 Mar 2022",
      "runtime": 176,
      "language": "English",
      "genre": "Action, Crime, Drama",
      "director": "Matt Reeves",
      "poster": "https://m.media-amazon.com/images/M/MV5BMDdmMTBiNTYtMDIzNi00NGVlLWIzMDYtZTk3MTQ3NGQxZGEwXkEyXkFqcGdeQXVyMzMwOTU5MDk@._V1_SX300.jpg"
  },
  {
      "_id": "62807ffa0a225942747116e7",
      "title": "A Better Tomorrow",
      "year": "1986",
      "released": "02 Aug 1986",
      "runtime": 95,
      "language": "Cantonese, Mandarin, English",
      "genre": "Action, Crime, Drama",
      "director": "John Woo",
      "poster": "https://m.media-amazon.com/images/M/MV5BZTEzMTYwZDItODIyYy00MjRkLTljOWMtZDI0ZmNjN2JjOTEyXkEyXkFqcGdeQXVyNzgzODI1OTE@._V1_SX300.jpg"
  },
  {
      "_id": "628086394020d2002fa0ddb7",
      "title": "Pirates of the Caribbean: Dead Men Tell No Tales",
      "year": "2017",
      "released": "26 May 2017",
      "runtime": 129,
      "language": "English, Spanish",
      "genre": "Action, Adventure, Fantasy",
      "director": "Joachim Rønning, Espen Sandberg",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTYyMTcxNzc5M15BMl5BanBnXkFtZTgwOTg2ODE2MTI@._V1_SX300.jpg"
  },
  {
      "_id": "62875b062d7642002f3e9f10",
      "title": "Captain Marvel",
      "year": "2019",
      "released": "08 Mar 2019",
      "runtime": 123,
      "language": "English",
      "genre": "Action, Adventure, Sci-Fi",
      "director": "Anna Boden, Ryan Fleck",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTE0YWFmOTMtYTU2ZS00ZTIxLWE3OTEtYTNiYzBkZjViZThiXkEyXkFqcGdeQXVyODMzMzQ4OTI@._V1_SX300.jpg"
  },
  {
      "_id": "628920f7769cce123f3d0e57",
      "title": "Iron Man 2",
      "year": "1999",
      "released": "6 May 1999",
      "runtime": 500,
      "language": "English, French, Russian",
      "genre": "Action, Adventure, Sci-Fi",
      "director": "Jon Favreau",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTM0MDgwNjMyMl5BMl5BanBnXkFtZTcwNTg3NzAzMw@@._V1_SX300.jpg"
  },
  {
      "_id": "628927d727d4c8491f624cb9",
      "title": "Friction",
      "year": "2010",
      "released": "27 Feb 2010",
      "runtime": 89,
      "language": "English",
      "genre": "Comedy, Drama, Mystery",
      "director": "Cullen Hoback",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTc5NzcxNzYxOV5BMl5BanBnXkFtZTcwMjE3ODk1Mw@@._V1_SX300.jpg"
  },
  {
      "_id": "6289a49d14216801956746a0",
      "title": "Undefined",
      "year": null,
      "released": null,
      "runtime": null,
      "language": null,
      "genre": null,
      "director": null,
      "poster": "https://m.media-amazon.com/images/M/MV5BMTgzNzkxMzk5Nl5BMl5BanBnXkFtZTgwMTQ2MzA2MDE@._V1_SX300.jpg"
  },
  {
      "_id": "6289b3756db20b0496122c96",
      "title": "Ashes of Time",
      "year": "1994",
      "released": "17 Sep 1994",
      "runtime": 100,
      "language": "Mandarin, Cantonese",
      "genre": "Action, Drama",
      "director": "Wong Kar-Wai ",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTc0NzMxMjI0MV5BMl5BanBnXkFtZTcwNzIwNzM5MQ@@._V1_SX300.jpg"
  },
  {
      "_id": "628a4e393aff210e5ee450fa",
      "title": "Home",
      "year": "2015",
      "released": "27 Mar 2015",
      "runtime": 94,
      "language": "English, French",
      "genre": "Animation, Adventure, Comedy",
      "director": "Tim Johnson 22",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjExOTQ4MDMyMV5BMl5BanBnXkFtZTgwMTE3NDM2MzE@._V1_SX300.jpg"
  },
  {
      "_id": "628a5824bd71bf23db7638ff",
      "title": "Home",
      "year": "2015",
      "released": "27 Mar 2015",
      "runtime": 94,
      "language": "English, French",
      "genre": "Animation, Adventure, Comedy",
      "director": "Tim Johnson 2",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjExOTQ4MDMyMV5BMl5BanBnXkFtZTgwMTE3NDM2MzE@._V1_SX300.jpg"
  },
  {
      "_id": "62829ba4ddee8c204f9b86fa",
      "title": "Captain America",
      "year": "1990",
      "released": "26 Jul 1991",
      "runtime": 97,
      "language": "English",
      "genre": "Action, Adventure, Sci-Fi",
      "director": "Albert Pyun",
      "poster": "https://m.media-amazon.com/images/M/MV5BYmRmYzA4NDItZmI3NS00NWIyLWIzZWEtNGIzZjZlYmY5MzE2XkEyXkFqcGdeQXVyMTEyNzgwMDUw._V1_SX300.jpg"
  },
  {
      "_id": "62891b0832e8570b2bb64316",
      "title": "Iron Man",
      "year": "4999",
      "released": "1 May 4999",
      "runtime": 999,
      "language": "English, Persian, Urdu, Arabic, Kurdish, Hindi, Hungarian",
      "genre": "Action, Adventure, Sci-Fi",
      "director": "Jon Favreau",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_SX300.jpg"
  },
  {
      "_id": "6289252d27d4c8491f624cb6",
      "title": "Batman",
      "year": "1989",
      "released": "23 Jun 1989",
      "runtime": 126,
      "language": "English, French, Spanish",
      "genre": "Comedy",
      "director": "Tim Burton",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTYwNjAyODIyMF5BMl5BanBnXkFtZTYwNDMwMDk2._V1_SX300.jpg"
  },
  {
      "_id": "6289c6a3bab2a26da869478b",
      "title": "Avatar",
      "year": "2009",
      "released": "18 Dec 2009",
      "runtime": 162,
      "language": "English, Spanish",
      "genre": "Action, Adventure, Fantasy",
      "director": "James Cameron",
      "poster": "https://m.media-amazon.com/images/M/MV5BZDA0OGQxNTItMDZkMC00N2UyLTg3MzMtYTJmNjg3Nzk5MzRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg"
  },
  {
      "_id": "628a462f8053320f4a1770cb",
      "title": "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
      "year": "1964",
      "released": "29 Jan 1964",
      "runtime": 95,
      "language": "English, Russian",
      "genre": "Comedy",
      "director": "Stanley Kubrick",
      "poster": "https://m.media-amazon.com/images/M/MV5BZWI3ZTMxNjctMjdlNS00NmUwLWFiM2YtZDUyY2I3N2MxYTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg"
  },
  {
      "_id": "628a476e3aff210e5ee450ef",
      "title": "Home",
      "year": "2015",
      "released": "27 Mar 2015",
      "runtime": 94,
      "language": "English, French",
      "genre": "Animation, Adventure, Comedy",
      "director": "Tim Johnson",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjExOTQ4MDMyMV5BMl5BanBnXkFtZTgwMTE3NDM2MzE@._V1_SX300.jpg"
  },
  {
      "_id": "628a49e73aff210e5ee450f4",
      "title": "Home",
      "year": "2015",
      "released": "27 Mar 2015",
      "runtime": 94,
      "language": "English, French",
      "genre": "Animation, Adventure, Comedy",
      "director": "Tim Johnson",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjExOTQ4MDMyMV5BMl5BanBnXkFtZTgwMTE3NDM2MzE@._V1_SX300.jpg"
  },
  {
      "_id": "628a4aa43aff210e5ee450f6",
      "title": "Home",
      "year": "2015",
      "released": "27 Mar 2015",
      "runtime": 94,
      "language": "English, French",
      "genre": "Animation, Adventure, Comedy",
      "director": "Tim Johnson 2",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjExOTQ4MDMyMV5BMl5BanBnXkFtZTgwMTE3NDM2MzE@._V1_SX300.jpg"
  },
  {
      "_id": "60bd930db1b0d030af499dff",
      "title": "Star Wars: Episode VIII - The Last Jedi",
      "year": "2017",
      "released": "15 Dec 2017",
      "runtime": 152,
      "language": "English",
      "genre": "Action, Adventure, Fantasy",
      "director": "Rian Johnson",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjQ1MzcxNjg4N15BMl5BanBnXkFtZTgwNzgwMjY4MzI@._V1_SX300.jpg"
  },
  {
      "_id": "60f2dc9f81d4502964d8872a",
      "director": "David Yates",
      "genre": "Adventure, Drama, Fantasy, Mystery",
      "language": "English",
      "poster": "https://m.media-amazon.com/images/M/MV5BMGVmMWNiMDktYjQ0Mi00MWIxLTk0N2UtN2ZlYTdkN2IzNDNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
      "released": "15 Jul 2011",
      "runtime": 130,
      "title": "Harry Potter and the Deathly Hallows: Part 2",
      "year": "2011"
  },
  {
      "_id": "60f2dc3281d4502964d88728",
      "director": "David Yates",
      "genre": "Adventure, Drama, Fantasy, Mystery",
      "language": "English",
      "poster": "https://m.media-amazon.com/images/M/MV5BMGVmMWNiMDktYjQ0Mi00MWIxLTk0N2UtN2ZlYTdkN2IzNDNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
      "released": "15 Jul 2011",
      "runtime": 130,
      "title": "Harry Potter and the Deathly Hallows: Part 2",
      "year": "2011"
  },
  {
      "_id": "60b500d0bceb63114b61b1de",
      "title": "Star Trek",
      "year": "2009",
      "released": "08 May 2009",
      "runtime": 127,
      "language": "English",
      "genre": "Action, Adventure, Sci-Fi",
      "director": "J.J. Abrams",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjE5NDQ5OTE4Ml5BMl5BanBnXkFtZTcwOTE3NDIzMw@@._V1_SX300.jpg"
  },
  {
      "_id": "628086514020d2002fa0ddb8",
      "title": "Sweeney Todd: The Demon Barber of Fleet Street",
      "year": "2007",
      "released": "21 Dec 2007",
      "runtime": 116,
      "language": "English, Italian",
      "genre": "Drama, Horror, Musical",
      "director": "Tim Burton",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTg3NjUxMzM5NV5BMl5BanBnXkFtZTcwMzQ1NjQzMw@@._V1_SX300.jpg"
  },
  {
      "_id": "628926fa27d4c8491f624cb8",
      "title": "Iron Man",
      "year": "2008",
      "released": "02 May 2008",
      "runtime": 126,
      "language": "English, Persian, Urdu, Arabic, Kurdish, Hindi, Hungarian",
      "genre": "Action, Adventure, Sci-Fi",
      "director": "Jon Favreau",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_SX300.jpg"
  },
  {
      "_id": "60bdaddeb1b0d030af499e02",
      "title": "Harry Potter and the Goblet of Fire",
      "year": "2005",
      "released": "18 Nov 2005",
      "runtime": 157,
      "language": "English, French",
      "genre": "Adventure, Family, Fantasy, Mystery",
      "director": "Mike Newell",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTI1NDMyMjExOF5BMl5BanBnXkFtZTcwOTc4MjQzMQ@@._V1_SX300.jpg"
  },
  {
      "_id": "60edac4f8bd3549e37241701",
      "title": "Edge",
      "year": "2040",
      "released": "05 Nov 2015",
      "runtime": 62,
      "language": "English",
      "genre": "Western",
      "director": "Shane Black",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTg3NDg3NDA4Ml5BMl5BanBnXkFtZTgwNDc2MjAyNzE@._V1_SX300.jpg"
  },
  {
      "_id": "60d9ccb98bd3549e372416ca",
      "title": "Cruella",
      "year": "2021",
      "released": "28 May 2021",
      "runtime": 134,
      "language": "English",
      "genre": "Comedy, Crime",
      "director": "Craig Gillespie",
      "poster": "https://m.media-amazon.com/images/M/MV5BOWI5YTUxOWEtZmRiZS00ZmQxLWE2NzctYTRiODA2NzE1ZjczXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg"
  },
  {
      "_id": "62885c4cb159fa00273f84a3",
      "title": "Avatar",
      "year": "1999",
      "released": "9 Sep 1999",
      "runtime": 99,
      "language": "English, Spanish",
      "genre": "Action, Adventure, Fantasy",
      "director": "James Cameron",
      "poster": "https://m.media-amazon.com/images/M/MV5BZDA0OGQxNTItMDZkMC00N2UyLTg3MzMtYTJmNjg3Nzk5MzRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg"
  },
  {
      "_id": "6289264927d4c8491f624cb7",
      "title": "Iron Man",
      "year": "2008",
      "released": "02 May 2008",
      "runtime": 126,
      "language": "English, Persian, Urdu, Arabic, Kurdish, Hindi, Hungarian",
      "genre": "Action, Adventure, Sci-Fi",
      "director": "Jon Favreau",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_SX300.jpg"
  },
  {
      "_id": "628a42d03aff210e5ee450eb",
      "title": "Home",
      "year": "2015",
      "released": "27 Mar 2015",
      "runtime": 94,
      "language": "English, French",
      "genre": "Animation, Adventure, Comedy",
      "director": "Tim Johnson 2",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjExOTQ4MDMyMV5BMl5BanBnXkFtZTgwMTE3NDM2MzE@._V1_SX300.jpg"
  },
  {
      "_id": "628a467e3aff210e5ee450ec",
      "title": "Home",
      "year": "2015",
      "released": "27 Mar 2015",
      "runtime": 94,
      "language": "English, French",
      "genre": "Animation, Adventure, Comedy",
      "director": "Tim Johnson 2",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjExOTQ4MDMyMV5BMl5BanBnXkFtZTgwMTE3NDM2MzE@._V1_SX300.jpg"
  },
  {
      "_id": "60f2dc4281d4502964d88729",
      "director": "David Yates",
      "genre": "Adventure, Drama, Fantasy, Mystery",
      "language": "English",
      "poster": "https://m.media-amazon.com/images/M/MV5BMGVmMWNiMDktYjQ0Mi00MWIxLTk0N2UtN2ZlYTdkN2IzNDNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
      "released": "15 Jul 2011",
      "runtime": 130,
      "title": "Harry Potter and the Deathly Hallows: Part 2",
      "year": "2011"
  },
  {
      "_id": "6104e54e81d4502964d8874a",
      "title": "Home",
      "year": "2015",
      "released": "27 Mar 2015",
      "runtime": 94,
      "language": "English, French",
      "genre": "Animation, Adventure, Comedy",
      "director": "Tim Johnson",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjExOTQ4MDMyMV5BMl5BanBnXkFtZTgwMTE3NDM2MzE@._V1_SX300.jpg"
  },
  {
      "_id": "625aef68fefee031204ec587",
      "title": "Dog",
      "year": "2022",
      "released": "18 Feb 2022",
      "runtime": 101,
      "language": "English",
      "genre": "Comedy",
      "director": "Reid Carolin, Channing Tatum",
      "poster": "https://m.media-amazon.com/images/M/MV5BYjA2MDM2YjctYzNhNC00NGEzLWFmYWEtODExODFkNmUyOGE2XkEyXkFqcGdeQXVyODk2NDQ3MTA@._V1_SX300.jpg"
  },
  {
      "_id": "6288a6a537a52f15d8b3180e",
      "title": "Cinderella",
      "year": "2015",
      "released": "13 Mar 2015",
      "runtime": 105,
      "language": "English",
      "genre": "Adventure",
      "director": "Kenneth Branagh",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjMxODYyODEzN15BMl5BanBnXkFtZTgwMDk4OTU0MzE@._V1_SX300.jpg"
  },
  {
      "_id": "6289c3a1aa0c010f821b7a88",
      "title": "The Dark Knight",
      "year": "2008",
      "released": "18 Jul 2008",
      "runtime": 152,
      "language": "English, Mandarin",
      "genre": "Drama",
      "director": "Christopher Nolan",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg"
  },
  {
      "_id": "628a42cf3aff210e5ee450ea",
      "title": "Home",
      "year": "2015",
      "released": "27 Mar 2015",
      "runtime": 94,
      "language": "English, French",
      "genre": "Animation, Adventure, Comedy",
      "director": "Tim Johnson 2",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjExOTQ4MDMyMV5BMl5BanBnXkFtZTgwMTE3NDM2MzE@._V1_SX300.jpg"
  },
  {
      "_id": "628a4b383aff210e5ee450f8",
      "title": "Home",
      "year": "2015",
      "released": "27 Mar 2015",
      "runtime": 94,
      "language": "English, French",
      "genre": "Animation, Adventure, Comedy",
      "director": "Tim Johnson 2",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjExOTQ4MDMyMV5BMl5BanBnXkFtZTgwMTE3NDM2MzE@._V1_SX300.jpg"
  },
  {
      "_id": "628a6653fc408f29278696bb",
      "title": "Home",
      "year": "2015",
      "released": "27 Mar 2015",
      "runtime": 94,
      "language": "English, French",
      "genre": "Animation, Adventure, Comedy",
      "director": "Tim Johnson 2",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjExOTQ4MDMyMV5BMl5BanBnXkFtZTgwMTE3NDM2MzE@._V1_SX300.jpg"
  },
  {
      "_id": "60f2de3481d4502964d8872b",
      "director": "David Yates",
      "genre": "Adventure, Drama, Fantasy, Mystery",
      "language": "English",
      "poster": "https://m.media-amazon.com/images/M/MV5BMGVmMWNiMDktYjQ0Mi00MWIxLTk0N2UtN2ZlYTdkN2IzNDNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
      "released": "15 Jul 2011",
      "runtime": 130,
      "title": "Harry Potter and the Deathly Hallows: Part 2",
      "year": "2011"
  },
  {
      "_id": "62829358e5354112e3e7fe57",
      "title": "Avatar",
      "year": "2009",
      "released": "18 Dec 2009",
      "runtime": 162,
      "language": "English, Spanish",
      "genre": "Action, Adventure, Fantasy",
      "director": "James Cameron",
      "poster": "https://m.media-amazon.com/images/M/MV5BZDA0OGQxNTItMDZkMC00N2UyLTg3MzMtYTJmNjg3Nzk5MzRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg"
  },
  {
      "_id": "6287e55ab9c38a039807e9b7",
      "title": "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
      "year": "1964",
      "released": "29 Jan 1964",
      "runtime": 95,
      "language": "English, Russian",
      "genre": "Comedy",
      "director": "Stanley Kubrick",
      "poster": "https://m.media-amazon.com/images/M/MV5BZWI3ZTMxNjctMjdlNS00NmUwLWFiM2YtZDUyY2I3N2MxYTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg"
  },
  {
      "_id": "6289260c685ccf0031e14f9b",
      "title": "Avatar",
      "year": "1999",
      "released": "17 Dec 1999",
      "runtime": 100,
      "language": "English, Spanish",
      "genre": "Action, Adventure, Fantasy",
      "director": "James Cameron",
      "poster": "https://m.media-amazon.com/images/M/MV5BZDA0OGQxNTItMDZkMC00N2UyLTg3MzMtYTJmNjg3Nzk5MzRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg"
  },
  {
      "_id": "6289bdd1aa0c010f821b7a85",
      "title": "The Eagle Shooting Heroes",
      "year": "1993",
      "released": "05 Feb 1993",
      "runtime": 103,
      "language": "Cantonese",
      "genre": "Action, Comedy, Fantasy",
      "director": "Jeffrey",
      "poster": "https://m.media-amazon.com/images/M/MV5BODc0YzY5ZGEtNzA3NS00NWQyLThhODgtZWU1MmJhZDA1MGMwXkEyXkFqcGdeQXVyMjQwMjk0NjI@._V1_SX300.jpg"
  },
  {
      "_id": "60cfff649149802efc9f0270",
      "title": "2012",
      "year": "2009",
      "released": "13 Nov 2009",
      "runtime": 158,
      "language": "English, French, Tibetan, Mandarin, Russian, Hindi, Portuguese, Latin, Italian, Spanish",
      "genre": "Action, Adventure, Sci-Fi",
      "director": "Roland Emmerich",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTY0MjEyODQzMF5BMl5BanBnXkFtZTcwMTczMjQ4Mg@@._V1_SX300.jpg"
  },
  {
      "_id": "628084a34020d2002fa0ddb5",
      "title": "Everything Everywhere All at Once",
      "year": "2022",
      "released": "25 Mar 2022",
      "runtime": 139,
      "language": "English, Mandarin, Cantonese",
      "genre": "Action, Adventure, Comedy",
      "director": "Dan Kwan, Daniel Scheinert",
      "poster": "https://m.media-amazon.com/images/M/MV5BYTdiOTIyZTQtNmQ1OS00NjZlLWIyMTgtYzk5Y2M3ZDVmMDk1XkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_SX300.jpg"
  },
  {
      "_id": "6289c29aaa0c010f821b7a87",
      "title": "The Dark Knight Rises",
      "year": "2012",
      "released": "20 Jul 2012",
      "runtime": 164,
      "language": "English, Arabic",
      "genre": "Action, Crime, Drama",
      "director": "Christopher",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_SX300.jpg"
  },
  {
      "_id": "628a4ce23aff210e5ee450f9",
      "title": "Home",
      "year": "2015",
      "released": "27 Mar 2015",
      "runtime": 94,
      "language": "English, French",
      "genre": "Animation, Adventure, Comedy",
      "director": "Tim Johnson 2",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjExOTQ4MDMyMV5BMl5BanBnXkFtZTgwMTE3NDM2MzE@._V1_SX300.jpg"
  },
  {
      "_id": "60d9c2088bd3549e372416c6",
      "title": "The Maze Runner",
      "year": "2014",
      "released": "19 Sep 2014",
      "runtime": 113,
      "language": "English",
      "genre": "Action, Mystery, Sci-Fi, Thriller",
      "director": "Wes Ball",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjUyNTA3MTAyM15BMl5BanBnXkFtZTgwOTEyMTkyMjE@._V1_SX300.jpg"
  },
  {
      "_id": "60bd91b6b1b0d030af499dfb",
      "title": "Star Trek Beyond",
      "year": "2016",
      "released": "22 Jul 2016",
      "runtime": 122,
      "language": "English",
      "genre": "Action, Adventure, Sci-Fi, Thriller",
      "director": "Justin Lin",
      "poster": "https://m.media-amazon.com/images/M/MV5BODgzMTZmMGMtNTM4Ni00ZjIxLWIyYmUtZjcxMDEwMjkxMzQyXkEyXkFqcGdeQXVyMjMwNDgzNjc@._V1_SX300.jpg"
  },
  {
      "_id": "60f13be981d4502964d886fa",
      "title": "Fight Club",
      "year": "2000",
      "released": "15 Oct 2000",
      "runtime": 140,
      "language": "English",
      "genre": "Drama",
      "director": "David Fincher Alan",
      "poster": "https://m.media-amazon.com/images/M/MV5BMmEzNTkxYjQtZTc0MC00YTVjLTg5ZTEtZWMwOWVlYzY0NWIwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg"
  },
  {
      "_id": "60d002319149802efc9f0272",
      "title": "Captain Marvel",
      "year": "2019",
      "released": "08 Mar 2019",
      "runtime": 123,
      "language": "English",
      "genre": "Action, Adventure, Sci-Fi",
      "director": "Anna Boden, Ryan Fleck",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTE0YWFmOTMtYTU2ZS00ZTIxLWE3OTEtYTNiYzBkZjViZThiXkEyXkFqcGdeQXVyODMzMzQ4OTI@._V1_SX300.jpg"
  },
  {
      "_id": "60f2f4af81d4502964d8872e",
      "director": "George Lucas",
      "genre": "Action, Adventure, Fantasy, Sci-Fi",
      "language": "English",
      "poster": "https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
      "released": "25 May 1977",
      "runtime": 121,
      "title": "Star Wars: Episode IV - A New Hope",
      "year": "1977"
  },
  {
      "_id": "60f2db0d81d4502964d88725",
      "director": "David Yates",
      "genre": "Adventure, Drama, Fantasy, Mystery",
      "language": "English",
      "poster": "https://m.media-amazon.com/images/M/MV5BMGVmMWNiMDktYjQ0Mi00MWIxLTk0N2UtN2ZlYTdkN2IzNDNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
      "released": "15 Jul 2011",
      "runtime": 130,
      "title": "Harry Potter and the Deathly Hallows: Part 2",
      "year": "2011"
  },
  {
      "_id": "60f44c0881d4502964d88742",
      "title": "Star Wars: Episode IV - A New Hope",
      "year": "1977",
      "released": "25 May 1977",
      "runtime": 121,
      "language": "English",
      "genre": "Action, Adventure, Fantasy, Sci-Fi",
      "director": "George Lucas",
      "poster": "https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg"
  },
  {
      "_id": "60dd2dab8bd3549e372416ce",
      "title": "The Divergent Series: Insurgent",
      "year": "2015",
      "released": "20 Mar 2015",
      "runtime": 119,
      "language": "English",
      "genre": "Action, Adventure, Sci-Fi, Thriller",
      "director": "Robert Schwentke",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTgxOTYxMTg3OF5BMl5BanBnXkFtZTgwMDgyMzA2NDE@._V1_SX300.jpg"
  },
  {
      "_id": "60f04a728bd3549e37241714",
      "title": "Star Wars: Episode IV - A New Hope",
      "year": "1977",
      "released": "25 May 1977",
      "runtime": 121,
      "language": "English",
      "genre": "Action, Adventure, Fantasy, Sci-Fi",
      "director": "George Lucas",
      "poster": "https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg"
  },
  {
      "_id": "60f446e181d4502964d8873f",
      "title": "Music",
      "year": "2021",
      "released": "12 Feb 2021",
      "runtime": 107,
      "language": "English, Mandarin",
      "genre": "Drama, Musical",
      "director": "Sia",
      "poster": "https://m.media-amazon.com/images/M/MV5BOTIwZjFmNmYtZTI3YS00MGFiLTllYjUtZGNlNWJiMmM2ZmY1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg"
  },
  {
      "_id": "626cf796405762003fc18f32",
      "title": "Harry Potter and the Deathly Hallows: Part 2",
      "year": "2011",
      "released": "15 Jul 2011",
      "runtime": 130,
      "language": "English, Latin",
      "genre": "Adventure, Fantasy, Mystery",
      "director": "Hello World",
      "poster": "https://m.media-amazon.com/images/M/MV5BMGVmMWNiMDktYjQ0Mi00MWIxLTk0N2UtN2ZlYTdkN2IzNDNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg"
  },
  {
      "_id": "62721e0952fc3700387f9740",
      "title": "CODA",
      "year": "2021",
      "released": "13 Aug 2021",
      "runtime": 111,
      "language": "American Sign , English",
      "genre": "Comedy, Drama, Music",
      "director": "Sian Heder",
      "poster": "https://m.media-amazon.com/images/M/MV5BYzkyNzNiMDItMGU1Yy00NmEyLWE4N2ItMjkzMDZmMmVhNDU4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg"
  },
  {
      "_id": "62721f65ee480204feac6e92",
      "title": "Parasite",
      "year": "2019",
      "released": "08 Nov 2019",
      "runtime": 132,
      "language": "Korean, English",
      "genre": "Comedy, Drama, Horror",
      "director": "Bong Joon Ho",
      "poster": "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg"
  },
  {
      "_id": "628296a4e5354112e3e7fe58",
      "title": "Spider-Man: No Way Home",
      "year": "2021",
      "released": "17 Dec 2021",
      "runtime": 148,
      "language": "English",
      "genre": "Action, Adventure, Fantasy",
      "director": "Jon Watts",
      "poster": "https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_SX300.jpg"
  },
  {
      "_id": "628a377aa9f33000bec9ec4c",
      "title": "Happy",
      "year": "2012",
      "released": "11 Feb 2012",
      "runtime": 76,
      "language": "Portuguese, Mandarin, Japanese, French, Nama, Danish, English",
      "genre": "Documentary",
      "director": "Roko Belic",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjI1NTg1MzcwM15BMl5BanBnXkFtZTcwMjA2OTU4NQ@@._V1_SX300.jpg"
  },
  {
      "_id": "628a3eefa9f33000bec9ec53",
      "title": "Cinderella",
      "year": "2012",
      "released": "11 Feb 2012",
      "runtime": 76,
      "language": "Portuguese, Mandarin, Japanese, French, Nama, Danish, English",
      "genre": "Documentary, Drama, Family",
      "director": "Roko Belic",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjMxODYyODEzN15BMl5BanBnXkFtZTgwMDk4OTU0MzE@._V1_SX300.jpg"
  },
  {
      "_id": "628a47053aff210e5ee450ee",
      "title": "Home",
      "year": "2015",
      "released": "27 Mar 2015",
      "runtime": 94,
      "language": "English, French",
      "genre": "Animation, Adventure, Comedy",
      "director": "Tim Johnson",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjExOTQ4MDMyMV5BMl5BanBnXkFtZTgwMTE3NDM2MzE@._V1_SX300.jpg"
  },
  {
      "_id": "60bd9337b1b0d030af499e00",
      "title": "Rogue One: A Star Wars Story",
      "year": "2016",
      "released": "16 Dec 2016",
      "runtime": 133,
      "language": "English",
      "genre": "Action, Adventure, Sci-Fi",
      "director": "Gareth Edwards",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjEwMzMxODIzOV5BMl5BanBnXkFtZTgwNzg3OTAzMDI@._V1_SX300.jpg"
  },
  {
      "_id": "60f11db181d4502964d886f5",
      "title": "Avengers: Infinity War",
      "year": "2018",
      "released": "27 Apr 2018",
      "runtime": 149,
      "language": "English",
      "genre": "Action, Adventure, Sci-Fi",
      "director": "Anthony Russo, Joe Russo",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg"
  },
  {
      "_id": "60bf035578eb0e32b2cf2fed",
      "title": "God of Gamblers II",
      "year": "1990",
      "released": "13 Dec 1990",
      "runtime": 99,
      "language": "Cantonese, English",
      "genre": "Action, Comedy, Drama",
      "director": "Jing Wong",
      "poster": "https://m.media-amazon.com/images/M/MV5BZmNlYzg4MWEtMThjNS00MGUxLTk3YTMtNTNkYTg4MjdmNGM5XkEyXkFqcGdeQXVyMjUyNDk2ODc@._V1_SX300.jpg"
  },
  {
      "_id": "60d9cad88bd3549e372416c9",
      "title": "Batman",
      "year": "1989",
      "released": "23 Jun 1989",
      "runtime": 126,
      "language": "English, French, Spanish",
      "genre": "Action, Adventure",
      "director": "Tim Burton",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTYwNjAyODIyMF5BMl5BanBnXkFtZTYwNDMwMDk2._V1_SX300.jpg"
  },
  {
      "_id": "60f2f6bf81d4502964d88730",
      "director": "Jon Favreau",
      "genre": "Action, Adventure, Sci-Fi",
      "language": "English, Persian, Urdu, Arabic, Kurdish, Hindi, Hungarian",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_SX300.jpg",
      "released": "02 May 2008",
      "runtime": 126,
      "title": "Iron Man",
      "year": "2008"
  },
  {
      "_id": "628089864020d2002fa0ddb9",
      "title": "Donald Trump's The Art of the Deal: The Movie",
      "year": "2016",
      "released": "10 Feb 2016",
      "runtime": 50,
      "language": "English",
      "genre": "Comedy",
      "director": "Jeremy Konner",
      "poster": "https://m.media-amazon.com/images/M/MV5BODcyNTk1ZGYtYzcwYy00Y2FiLTk4MjQtNmRlZmMyYWY1NzBkXkEyXkFqcGdeQXVyMjU3NDQ3MDg@._V1_SX300.jpg"
  },
  {
      "_id": "628865f2bdd00a002f318c65",
      "title": "La La Land",
      "year": "2016",
      "released": "25 Dec 2016",
      "runtime": 128,
      "language": "English, Cantonese",
      "genre": "Comedy, Drama, Music",
      "director": "Damien Chazelle",
      "poster": "https://m.media-amazon.com/images/M/MV5BMzUzNDM2NzM2MV5BMl5BanBnXkFtZTgwNTM3NTg4OTE@._V1_SX300.jpg"
  },
  {
      "_id": "6288a75337a52f15d8b3180f",
      "title": "Frozen",
      "year": "2013",
      "released": "27 Nov 2013",
      "runtime": 102,
      "language": "English, Norwegian",
      "genre": "Animation",
      "director": "Chris Buck",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTQ1MjQwMTE5OF5BMl5BanBnXkFtZTgwNjk3MTcyMDE@._V1_SX300.jpg"
  },
  {
      "_id": "628a3a3ea9f33000bec9ec4f",
      "title": "Cinderella",
      "year": "2015",
      "released": "13 Mar 2015",
      "runtime": 105,
      "language": "English",
      "genre": "Adventure, Drama, Family",
      "director": "Kenneth Branagh",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjMxODYyODEzN15BMl5BanBnXkFtZTgwMDk4OTU0MzE@._V1_SX300.jpg"
  },
  {
      "_id": "628a3b3aa9f33000bec9ec50",
      "title": "Cinderella",
      "year": "2015",
      "released": "11 Feb 2012",
      "runtime": 76,
      "language": "English",
      "genre": "Family",
      "director": "Kenneth Branagh",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjMxODYyODEzN15BMl5BanBnXkFtZTgwMDk4OTU0MzE@._V1_SX300.jpg"
  },
  {
      "_id": "628a4556bab2a26da8694790",
      "title": "Avatar",
      "year": "2009",
      "released": "18 Dec 2009",
      "runtime": 162,
      "language": "English, Spanish",
      "genre": "Action, Adventure, Fantasy",
      "director": "James Cameron",
      "poster": "https://m.media-amazon.com/images/M/MV5BZDA0OGQxNTItMDZkMC00N2UyLTg3MzMtYTJmNjg3Nzk5MzRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg"
  },
  {
      "_id": "628a4acd3aff210e5ee450f7",
      "title": "Home",
      "year": "2015",
      "released": "27 Mar 2015",
      "runtime": 94,
      "language": "English, French",
      "genre": "Animation, Adventure, Comedy",
      "director": "Tim Johnson",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjExOTQ4MDMyMV5BMl5BanBnXkFtZTgwMTE3NDM2MzE@._V1_SX300.jpg"
  },
  {
      "_id": "60f2f44c81d4502964d8872d",
      "director": "David Yates",
      "genre": "Adventure, Drama, Fantasy, Mystery",
      "language": "English",
      "poster": "https://m.media-amazon.com/images/M/MV5BMGVmMWNiMDktYjQ0Mi00MWIxLTk0N2UtN2ZlYTdkN2IzNDNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
      "released": "15 Jul 2011",
      "runtime": 130,
      "title": "Harry Potter and the Deathly Hallows: Part 2",
      "year": "2011"
  },
  {
      "_id": "60edac268bd3549e37241700",
      "title": "Edge",
      "year": "2030",
      "released": "05 Nov 2015",
      "runtime": 62,
      "language": "English",
      "genre": "Western",
      "director": "Shane Black",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTg3NDg3NDA4Ml5BMl5BanBnXkFtZTgwNDc2MjAyNzE@._V1_SX300.jpg"
  },
  {
      "_id": "626cf2380907c21a8abc1d48",
      "title": "The Golden Era",
      "year": "2014",
      "released": "01 Oct 2014",
      "runtime": 177,
      "language": "Mandarin",
      "genre": "Biography, Drama, Romance",
      "director": "Ann Hui",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTk0NzA4NTEwNF5BMl5BanBnXkFtZTgwMTA0MTc5MjE@._V1_SX300.jpg"
  },
  {
      "_id": "6277cf815559bf00d6396f3e",
      "title": "Lady Bird",
      "year": "2017",
      "released": "01 Dec 2017",
      "runtime": 94,
      "language": "English, Spanish",
      "genre": "Comedy, Drama",
      "director": "Greta Gerwig",
      "poster": "https://m.media-amazon.com/images/M/MV5BODhkZGE0NDQtZDc0Zi00YmQ4LWJiNmUtYTY1OGM1ODRmNGVkXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg"
  },
  {
      "_id": "6282996cddee8c204f9b86f9",
      "title": "Iron Man 3",
      "year": "2013",
      "released": "03 May 2013",
      "runtime": 130,
      "language": "English",
      "genre": "Action, Adventure, Sci-Fi",
      "director": "Shane Black",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjE5MzcyNjk1M15BMl5BanBnXkFtZTcwMjQ4MjcxOQ@@._V1_SX300.jpg"
  },
  {
      "_id": "6289b5696db20b0496122c97",
      "title": "From Beijing with Love",
      "year": "1994",
      "released": "14 Sep 1994",
      "runtime": 84,
      "language": "Cantonese, Mandarin, English",
      "genre": "Comedy",
      "director": "Stephen Chow, Lik-Chi Lee",
      "poster": "https://m.media-amazon.com/images/M/MV5BOTBjZjc2YTMtMzJmYy00MzNlLThkODgtYmE5MDcyZjhmYzIyXkEyXkFqcGdeQXVyNzgyNTQwMjE@._V1_SX300.jpg"
  },
  {
      "_id": "628a44f3bab2a26da869478f",
      "title": "Avatar",
      "year": "2009",
      "released": "18 Dec 2009",
      "runtime": 162,
      "language": "English, Spanish",
      "genre": "Action, Adventure, Fantasy",
      "director": "James Cameron",
      "poster": "https://m.media-amazon.com/images/M/MV5BZDA0OGQxNTItMDZkMC00N2UyLTg3MzMtYTJmNjg3Nzk5MzRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg"
  },
  {
      "_id": "628a46d18053320f4a1770cc",
      "title": "Cinderella",
      "year": "2015",
      "released": "13 Mar 2015",
      "runtime": "105 min",
      "language": "English",
      "genre": "Adventure, Drama, Family",
      "director": "Kenneth Branagh",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjMxODYyODEzN15BMl5BanBnXkFtZTgwMDk4OTU0MzE@._V1_SX300.jpg"
  },
  {
      "_id": "628a59a7bd71bf23db763900",
      "title": "Home",
      "year": "2015",
      "released": "27 Mar 2015",
      "runtime": 94,
      "language": "English, French",
      "genre": "Animation, Adventure, Comedy",
      "director": "Tim Johnson 2",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjExOTQ4MDMyMV5BMl5BanBnXkFtZTgwMTE3NDM2MzE@._V1_SX300.jpg"
  },
  {
      "_id": "60bdae5812f275fc7451c57d",
      "title": "Harry Potter and the Deathly Hallows: Part 1",
      "year": "2010",
      "released": "19 Nov 2010",
      "runtime": 146,
      "language": "English",
      "genre": "Adventure, Family, Fantasy, Mystery",
      "director": "David Yates",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTQ2OTE1Mjk0N15BMl5BanBnXkFtZTcwODE3MDAwNA@@._V1_SX300.jpg"
  },
  {
      "_id": "60f4316181d4502964d88737",
      "title": "Python",
      "year": "2000",
      "released": "01 Aug 2001",
      "runtime": 99,
      "language": "English",
      "genre": "Action, Comedy, Horror, Sci-Fi, Thriller",
      "director": "Richard Clabaugh",
      "poster": "https://m.media-amazon.com/images/M/MV5BZGZlNWU0ZWEtNzY4MC00NDdmLTgzOTktOTgzMjBlNGMxN2ZmL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"
  },
  {
      "_id": "62721f2cee480204feac6e91",
      "title": "Nomadland",
      "year": "2020",
      "released": "19 Feb 2021",
      "runtime": 107,
      "language": "English",
      "genre": "Drama",
      "director": "Chloé Zhao",
      "poster": "https://m.media-amazon.com/images/M/MV5BMDRiZWUxNmItNDU5Yy00ODNmLTk0M2ItZjQzZTA5OTJkZjkyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg"
  },
  {
      "_id": "6282982eddee8c204f9b86f7",
      "title": "Iron Man 2",
      "year": "2010",
      "released": "07 May 2010",
      "runtime": 124,
      "language": "English, French, Russian",
      "genre": "Action, Adventure, Sci-Fi",
      "director": "Jon Favreau",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTM0MDgwNjMyMl5BMl5BanBnXkFtZTcwNTg3NzAzMw@@._V1_SX300.jpg"
  },
  {
      "_id": "6289230fae36df1461cdc477",
      "title": "Pokémon Detective Pikachu",
      "year": "1999",
      "released": "9 Jul 1999",
      "runtime": 999,
      "language": "English, Japanese",
      "genre": "Action, Adventure, Comedy",
      "director": "Rob Letterman",
      "poster": "https://m.media-amazon.com/images/M/MV5BMDkxNzRmNDYtMDY0OS00N2JhLTkzZWUtMWE3MzZkNDk1MmJiXkEyXkFqcGdeQXVyNTA3MTU2MjE@._V1_SX300.jpg"
  },
  {
      "_id": "6289c8c7bab2a26da869478d",
      "title": "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
      "year": "1964",
      "released": "29 Jan 1964",
      "runtime": 95,
      "language": "English, Russian",
      "genre": "Comedy",
      "director": "Stanley Kubrick",
      "poster": "https://m.media-amazon.com/images/M/MV5BZWI3ZTMxNjctMjdlNS00NmUwLWFiM2YtZDUyY2I3N2MxYTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg"
  },
  {
      "_id": "628a3e74a9f33000bec9ec52",
      "title": "Happy",
      "year": "2012",
      "released": "11 Feb 2012",
      "runtime": 76,
      "language": "Portuguese, Mandarin, Japanese, French, Nama, Danish, English",
      "genre": "Documentary, Drama, Family",
      "director": "Roko Belic",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjI1NTg1MzcwM15BMl5BanBnXkFtZTcwMjA2OTU4NQ@@._V1_SX300.jpg"
  },
  {
      "_id": "628a42ce3aff210e5ee450e9",
      "title": "Home",
      "year": "2015",
      "released": "27 Mar 2015",
      "runtime": 94,
      "language": "English, French",
      "genre": "Animation, Adventure, Comedy",
      "director": "Tim Johnson 2",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjExOTQ4MDMyMV5BMl5BanBnXkFtZTgwMTE3NDM2MzE@._V1_SX300.jpg"
  },
  {
      "_id": "628a486d3aff210e5ee450f2",
      "title": "Home",
      "year": "2015",
      "released": "27 Mar 2015",
      "runtime": 94,
      "language": "English, French",
      "genre": "Animation, Adventure, Comedy",
      "director": "Tim Johnson",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjExOTQ4MDMyMV5BMl5BanBnXkFtZTgwMTE3NDM2MzE@._V1_SX300.jpg"
  },
  {
      "_id": "60f4582a81d4502964d88747",
      "title": "Star Wars: Episode IV - A New Hope",
      "year": "1977",
      "released": "25 May 1977",
      "runtime": 121,
      "language": "English",
      "genre": "Action, Adventure, Fantasy, Sci-Fi",
      "director": "George Lucas",
      "poster": "https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg"
  },
  {
      "_id": "60f544af81d4502964d88749",
      "title": "Bear",
      "year": "1000",
      "released": "04 Jun 2010",
      "runtime": "9000 min",
      "language": "chinese",
      "genre": "Action, Adventure, Drama, Horror, Thriller",
      "director": "Roel Reiné",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTcyNzU1NTI1NV5BMl5BanBnXkFtZTcwNDAyODg5Mg@@._V1_SX300.jpg"
  },
  {
      "_id": "6275f633fefee031204ec590",
      "title": "Fresh",
      "year": "2022",
      "released": "04 Mar 2022",
      "runtime": 114,
      "language": "English",
      "genre": "Comedy, Horror, Thriller",
      "director": "Mimi Cave",
      "poster": "https://m.media-amazon.com/images/M/MV5BZTgxMGQ2ZDctYWY4Yy00YTI4LWIxMmYtOWViMGI5ZDIwMmFiXkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_SX300.jpg"
  },
  {
      "_id": "6287e74cb9c38a039807e9b8",
      "title": "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
      "year": "1964",
      "released": "29 Jan 1964",
      "runtime": 95,
      "language": "English, Russian",
      "genre": "Comedy",
      "director": "Stanley Kubrick",
      "poster": "https://m.media-amazon.com/images/M/MV5BZWI3ZTMxNjctMjdlNS00NmUwLWFiM2YtZDUyY2I3N2MxYTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg"
  },
  {
      "_id": "6289285027d4c8491f624cba",
      "title": "Butterfly",
      "year": "1999",
      "released": "18 Aug 2000",
      "runtime": 96,
      "language": "Spanish, Galician, Latin",
      "genre": "Drama, War",
      "director": "José Luis Cuerda",
      "poster": "https://m.media-amazon.com/images/M/MV5BZTAwNzQ1MTktZDRmMi00OTZjLWJmNjctMGM3ZTQxNjNlYTA4XkEyXkFqcGdeQXVyMTA0MjU0Ng@@._V1_SX300.jpg"
  },
  {
      "_id": "6289af4b7f7d57005e370411",
      "title": "2046",
      "year": "2004",
      "released": "29 Sep 2004",
      "runtime": 129,
      "language": "Cantonese, Japanese, Mandarin",
      "genre": "Drama, Romance, Sci-Fi",
      "director": "Kar-Wai Wong",
      "poster": "https://m.media-amazon.com/images/M/MV5BM2NlYjY5N2QtZWIxNS00MWY3LTk5YTEtYWZkZTc3NTExZjI3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg"
  },
  {
      "_id": "628a3810a9f33000bec9ec4d",
      "title": "Cinderella",
      "year": "2015",
      "released": "11 Feb 2012",
      "runtime": 76,
      "language": "English",
      "genre": "Family",
      "director": "Kenneth Branagh",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjMxODYyODEzN15BMl5BanBnXkFtZTgwMDk4OTU0MzE@._V1_SX300.jpg"
  },
  {
      "_id": "628a481d3aff210e5ee450f1",
      "title": "Home",
      "year": "2015",
      "released": "27 Mar 2015",
      "runtime": 94,
      "language": "English, French",
      "genre": "Animation, Adventure, Comedy",
      "director": "Tim Johnson",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjExOTQ4MDMyMV5BMl5BanBnXkFtZTgwMTE3NDM2MzE@._V1_SX300.jpg"
  },
  {
      "_id": "628a48d93aff210e5ee450f3",
      "title": "Home",
      "year": "2015",
      "released": "27 Mar 2015",
      "runtime": 94,
      "language": "English, French",
      "genre": "Animation, Adventure, Comedy",
      "director": "Tim Johnson",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjExOTQ4MDMyMV5BMl5BanBnXkFtZTgwMTE3NDM2MzE@._V1_SX300.jpg"
  },
  {
      "_id": "628a4a20bab2a26da8694791",
      "title": "Avatar",
      "year": "2009",
      "released": "18 Dec 2009",
      "runtime": 162,
      "language": "English, Spanish",
      "genre": "Action, Adventure, Fantasy",
      "director": "James Cameron",
      "poster": "https://m.media-amazon.com/images/M/MV5BZDA0OGQxNTItMDZkMC00N2UyLTg3MzMtYTJmNjg3Nzk5MzRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg"
  },
  {
      "_id": "60f116ec81d4502964d886f4",
      "title": "Avengers: Endgame",
      "year": "2019",
      "released": "26 Apr 2019",
      "runtime": "181 min",
      "language": "English, Japanese, Xhosa, German",
      "genre": "Action, Adventure, Drama, Sci-Fi",
      "director": "Anthony Russo, Joe Russo",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg"
  },
  {
      "_id": "60f2f62381d4502964d8872f",
      "director": "David Yates",
      "genre": "Adventure, Drama, Fantasy, Mystery",
      "language": "English",
      "poster": "https://m.media-amazon.com/images/M/MV5BMGVmMWNiMDktYjQ0Mi00MWIxLTk0N2UtN2ZlYTdkN2IzNDNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
      "released": "15 Jul 2011",
      "runtime": 130,
      "title": "Harry Potter and the Deathly Hallows: Part 2",
      "year": "2011"
  },
  {
      "_id": "60f44d8d81d4502964d88743",
      "title": "Bat*21",
      "year": "1988",
      "released": "21 Oct 1988",
      "runtime": 0,
      "language": "English",
      "genre": "Drama, War",
      "director": "Peter Markle",
      "poster": "https://m.media-amazon.com/images/M/MV5BZDRmNjYwZDktOTYxZi00MTdlLWI5ZjYtYWU4MDE5MDc5NGM3L2ltYWdlXkEyXkFqcGdeQXVyNjQzNDI3NzY@._V1_SX300.jpg"
  },
  {
      "_id": "60d9cd848bd3549e372416cc",
      "title": "Tenet",
      "year": "2020",
      "released": "03 Sep 2020",
      "runtime": 150,
      "language": "English, Russian, Ukrainian, Estonian, Norwegian, Hindi",
      "genre": "Action, Sci-Fi, Thriller",
      "director": "Christopher Nolan",
      "poster": "https://m.media-amazon.com/images/M/MV5BYzg0NGM2NjAtNmIxOC00MDJmLTg5ZmYtYzM0MTE4NWE2NzlhXkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_SX300.jpg"
  },
  {
      "_id": "628918d732e8570b2bb64315",
      "title": "Pokémon Detective Pikachu",
      "year": "4999",
      "released": "9 May 4999",
      "runtime": 999,
      "language": "English, Japanese",
      "genre": "Action, Adventure, Comedy",
      "director": "Rob Letterman",
      "poster": "https://m.media-amazon.com/images/M/MV5BMDkxNzRmNDYtMDY0OS00N2JhLTkzZWUtMWE3MzZkNDk1MmJiXkEyXkFqcGdeQXVyNTA3MTU2MjE@._V1_SX300.jpg"
  },
  {
      "_id": "6289c0d5aa0c010f821b7a86",
      "title": "Underworld: Evolution",
      "year": "2006",
      "released": "20 Jan 2006",
      "runtime": 106,
      "language": "English, French, Hungarian",
      "genre": "Action, Fantasy, Thriller",
      "director": "Len",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjEzNDY1OTQwOV5BMl5BanBnXkFtZTcwNjcxMTIzMw@@._V1_SX300.jpg"
  },
  {
      "_id": "6289e3f9bab2a26da869478e",
      "title": "Avatar",
      "year": "2009",
      "released": "18 Dec 2009",
      "runtime": 162,
      "language": "English, Spanish",
      "genre": "Action, Adventure, Fantasy",
      "director": "James Cameron",
      "poster": "https://m.media-amazon.com/images/M/MV5BZDA0OGQxNTItMDZkMC00N2UyLTg3MzMtYTJmNjg3Nzk5MzRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg"
  },
  {
      "_id": "60bf03eb78eb0e32b2cf2fee",
      "title": "The Conman",
      "year": "1998",
      "released": "24 Dec 1998",
      "runtime": 107,
      "language": "Cantonese",
      "genre": "Comedy",
      "director": "Jing Wong",
      "poster": "https://m.media-amazon.com/images/M/MV5BNjc4YjliZjUtMjZmNi00MDA3LWE3NDItZGIwMDQ5Mjc3YzA1XkEyXkFqcGdeQXVyMTQwMTE4OTU@._V1_SX300.jpg"
  },
  {
      "_id": "6287dc37165cc3032df4636c",
      "title": "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
      "year": "1964",
      "released": "29 Jan 1964",
      "runtime": 95,
      "language": "English, Russian",
      "genre": "Comedy",
      "director": "Stanley Kubrick",
      "poster": "https://m.media-amazon.com/images/M/MV5BZWI3ZTMxNjctMjdlNS00NmUwLWFiM2YtZDUyY2I3N2MxYTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg"
  },
  {
      "_id": "62885fb8d96c480032f61ca3",
      "title": "Pokémon Detective Pikachu",
      "year": "3999",
      "released": "9 Sep 1999",
      "runtime": 99,
      "language": "Japanese, Japanese",
      "genre": "Action, Action, Action",
      "director": "Pokemon",
      "poster": "https://m.media-amazon.com/images/M/MV5BMDkxNzRmNDYtMDY0OS00N2JhLTkzZWUtMWE3MzZkNDk1MmJiXkEyXkFqcGdeQXVyNTA3MTU2MjE@._V1_SX300.jpg"
  },
  {
      "_id": "62891c9965a1650f1359c6d9",
      "title": "Avatar",
      "year": "2000",
      "released": "17 Dec 2000",
      "runtime": 399,
      "language": "English, Spanish",
      "genre": "Action, Adventure, Fantasy",
      "director": "James Cameron",
      "poster": "https://m.media-amazon.com/images/M/MV5BZDA0OGQxNTItMDZkMC00N2UyLTg3MzMtYTJmNjg3Nzk5MzRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg"
  },
  {
      "_id": "6289c6f6bab2a26da869478c",
      "title": "Avatar",
      "year": "2009",
      "released": "18 Dec 2009",
      "runtime": 162,
      "language": "English, Spanish",
      "genre": "Action, Adventure, Fantasy",
      "director": "James Cameron",
      "poster": "https://m.media-amazon.com/images/M/MV5BZDA0OGQxNTItMDZkMC00N2UyLTg3MzMtYTJmNjg3Nzk5MzRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg"
  },
  {
      "_id": "628a3c15a9f33000bec9ec51",
      "title": "Happy",
      "year": "2012",
      "released": "11 Feb 2012",
      "runtime": 76,
      "language": "Portuguese, Mandarin, Japanese, French, Nama, Danish, English",
      "genre": "Documentary, Drama, Family",
      "director": "Roko Belic",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjI1NTg1MzcwM15BMl5BanBnXkFtZTcwMjA2OTU4NQ@@._V1_SX300.jpg"
  },
  {
      "_id": "628a4a3f3aff210e5ee450f5",
      "title": "Home",
      "year": "2015",
      "released": "27 Mar 2015",
      "runtime": 94,
      "language": "English, French",
      "genre": "Animation, Adventure, Comedy",
      "director": "Tim Johnson",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjExOTQ4MDMyMV5BMl5BanBnXkFtZTgwMTE3NDM2MzE@._V1_SX300.jpg"
  },
  {
      "_id": "60f107dc81d4502964d886f3",
      "title": "The Rock",
      "year": "2000",
      "released": "07 Jun 1996",
      "runtime": 138,
      "language": "English",
      "genre": "Action, Adventure, Thriller",
      "director": "Michael Bay",
      "poster": "https://m.media-amazon.com/images/M/MV5BZDJjOTE0N2EtMmRlZS00NzU0LWE0ZWQtM2Q3MWMxNjcwZjBhXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg"
  },
  {
      "_id": "60b50127bceb63114b61b1df",
      "title": "Indiana Jones and the Raiders of the Lost Ark",
      "year": "1981",
      "released": "12 Jun 1981",
      "runtime": 115,
      "language": "English, German, Hebrew, Spanish, Arabic, Nepali",
      "genre": "Action, Adventure",
      "director": "Steven Spielberg",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjA0ODEzMTc1Nl5BMl5BanBnXkFtZTcwODM2MjAxNA@@._V1_SX300.jpg"
  },
  {
      "_id": "625aeed6fefee031204ec585",
      "title": "Uncharted",
      "year": "2022",
      "released": "18 Feb 2022",
      "runtime": 116,
      "language": "English, Spanish",
      "genre": "Action, Adventure",
      "director": "Ruben Fleischer",
      "poster": "https://m.media-amazon.com/images/M/MV5BMWEwNjhkYzYtNjgzYy00YTY2LThjYWYtYzViMGJkZTI4Y2MyXkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_SX300.jpg"
  },
  {
      "_id": "628085de4020d2002fa0ddb6",
      "title": "Murder on the Orient Express",
      "year": "2017",
      "released": "10 Nov 2017",
      "runtime": 114,
      "language": "English, French, Arabic, German",
      "genre": "Crime, Drama, Mystery",
      "director": "Kenneth Branagh",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTAxNDkxODIyMDZeQTJeQWpwZ15BbWU4MDQ2Mjg4NDIy._V1_SX300.jpg"
  },
  {
      "_id": "6287eaafb9c38a039807e9b9",
      "title": "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
      "year": "1964",
      "released": "29 Jan 1964",
      "runtime": 95,
      "language": "English, Russian",
      "genre": "Comedy",
      "director": "Stanley Kubrick",
      "poster": "https://m.media-amazon.com/images/M/MV5BZWI3ZTMxNjctMjdlNS00NmUwLWFiM2YtZDUyY2I3N2MxYTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg"
  },
  {
      "_id": "6288a7557a0dfc002017fcae",
      "title": "Dune",
      "year": "2999",
      "released": "1 Jan 2001",
      "runtime": 100,
      "language": "English, Mandarin",
      "genre": "Action, Adventure, Drama",
      "director": "Denis Villeneuve",
      "poster": "https://m.media-amazon.com/images/M/MV5BN2FjNmEyNWMtYzM0ZS00NjIyLTg5YzYtYThlMGVjNzE1OGViXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg"
  },
  {
      "_id": "628a46863aff210e5ee450ed",
      "title": "Home",
      "year": "2015",
      "released": "27 Mar 2015",
      "runtime": 94,
      "language": "English, French",
      "genre": "Animation, Adventure, Comedy",
      "director": "Tim Johnson 3",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjExOTQ4MDMyMV5BMl5BanBnXkFtZTgwMTE3NDM2MzE@._V1_SX300.jpg"
  },
  {
      "_id": "641a663154683f8a0cfb356e",
      "title": "Star Wars: The Clone Wars",
      "year": "2008–2020",
      "runtime": 23,
      "genre": "Animation, Action, Adventure",
      "director": "N/A",
      "language": "English",
      "poster": "https://m.media-amazon.com/images/M/MV5BZWFlNzRmOTItZjY1Ni00ZjZkLTk5MDgtOGFhOTYzNWFhYzhmXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg"
  },
  {
      "_id": "641a69259794e8fe9333b0a5",
      "title": "Solo: A Star Wars Story",
      "year": "2018",
      "runtime": 135,
      "genre": "Action, Adventure, Sci-Fi",
      "director": "Ron Howard",
      "language": "English",
      "poster": "https://m.media-amazon.com/images/M/MV5BOTM2NTI3NTc3Nl5BMl5BanBnXkFtZTgwNzM1OTQyNTM@._V1_SX300.jpg"
  }
]